name: Build amd64 module

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  release:
    types: [published]

# This regex matches either a semver (e.g. 1.2.3)
# or a release candidate in one of these forms:
# 1.2.3-rc or 1.2.3-rc1
# Adjust the regex below as needed.
# The pattern:
#   ^(?:[0-9]+\.[0-9]+\.[0-9]+|[0-9]+\.[0-9]+\.[0-9]+-rc(?:[0-9]+)?)$
# means: start-of-string, then either:
#    [0-9]+.[0-9]+.[0-9]+
# or [0-9]+.[0-9]+.[0-9]+-rc optionally followed by digits, then end-of-string.

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag format
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "Validating tag: $TAG"
          if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ ]]; then
            echo "Tag matches semver."
          else
            echo "Error: tag does not match semvar"
            exit 1
          fi

  publish:
    needs: validate-tag
    name: Upload module for linux/amd64
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/viamrobotics/ocean-prefilter:amd64
      options: --platform linux/amd64
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build
        run: make module.tar.gz
      - name: Upload
        uses: viamrobotics/upload-module@v1
        with:
          platform: linux/amd64 
          version: ${{ github.ref_name }} 
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
