name: golangci-lint

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  
on:
  push:
    branches:
      - main
      - master
  pull_request: 
    branches: 
      - main

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/viamrobotics/ocean-prefilter:arm64
      options: --platform linux/arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          args: --timeout 5m
