name: golangci-lint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint for linux/arm64
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    container:
      image: ghcr.io/viamrobotics/ocean-prefilter:arm64
      options: --platform linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched for proper VCS operations
      - name: Run golangci-lint
        run: |
          /github/home/golangci-lint-1.59.1-linux-arm64/golangci-lint run --timeout 10m
