name: Run lint & unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Run unit tests"
    runs-on: [buildjet-2vcpu-ubuntu-2204-arm]
    container:
      image: ghcr.io/viamrobotics/ocean-prefilter:arm64
      options: --platform linux/arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'



    - name: Run lint
      run: make lint

    - name: Run unit tests
      run: make test